packages:
  - apps/*
  - products/forgearc-node/apps/*
  - products/forgearc-node/packages/*
  - products/forgearc-node/modules/*
  - products/forgearc-node/infra/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
