name: Python CloudArc CI

on:
  push:
    paths:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: pip install -e ".[dev]"
      - name: Lint
        run: ruff check tests scripts
      - name: Test
        run: pytest
        env:
          IS_LOCAL: 'true'
          DB_USERNAME: postgres
          DB_PASSWORD: secret
          DB_HOST: localhost
          DB_NAME: arcforge
