name: Python CloudArc CI
on:
  push:
    paths: ['python-cloud-arc/**']
  pull_request:
    paths: ['python-cloud-arc/**']
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-cloud-arc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -e ".[dev]"
      - run: pytest
        env:
          IS_LOCAL: 'true'
